name: Bug Report
description: File a bug/issue report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        # Bug Report üêõ
        
        Thanks for taking the time to fill out this bug report!

        Please answer each question below to your best ability. It is okay to leave questions blank if you have to!

  - type: textarea
    id: description
    attributes:
      label: Describe the Issue
      description: Please describe the bug/issue in detail
      placeholder: Something is wrong with X when trying to do Y
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Action Configuration
      description: Please copy and paste your Action's configuration. Please omit any sensitive information if your configuration is not public.
      placeholder: |
        ```yaml
        - name: branch-deploy
          id: branch-deploy
          uses: github/branch-deploy@vX.X.X
          with:
            trigger: ".deploy"
            environment: "production"
            stable_branch: "main"
        ```

  - type: textarea
    id: logs
    attributes:
      label: Relevant Actions Log Output
      description: Please copy and paste any relevant log output. If your Action's workflow is public, please provide a direct link to the logs

  - type: textarea
    id: extra
    attributes:
      label: Extra Information
      description: Any extra information, links to issues, screenshots, etc
