# name: "sample-workflow"

# on:
#   issue_comment:
#     types: [created]

# permissions:
#   pull-requests: write
#   deployments: write
#   contents: write
#   checks: read
#   statuses: read

# jobs:
#   sample:
#     if: ${{ github.event.issue.pull_request }} # only run on pull request comments
#     environment: production-secrets
#     runs-on: ubuntu-latest
#     steps:
#       # Need to checkout for testing the Action in this repo
#       - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # pin@v3.0.2

#       # Start the branch deployment
#       - uses: ./
#         id: branch-deploy
#         with:
#           admins: grantbirki

#       # Check out the ref from the output of the IssueOps command
#       - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # pin@v3.0.2
#         if: ${{ steps.branch-deploy.outputs.continue == 'true' }}
#         with:
#           ref: ${{ steps.branch-deploy.outputs.ref }}

#       # Do some fake "noop" deployment logic here
#       - name: fake noop deploy
#         if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop == 'true' }}
#         run: echo "I am doing a fake noop deploy"

#       # Do some fake "regular" deployment logic here
#       - name: fake regular deploy
#         if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop != 'true' }}
#         run: echo "I am doing a fake regular deploy"
